experiment: adaptive_flipped_lasso_exp2_snr
generated_by: sweep.py snr
generated_at: '2026-03-26T18:18:14.644705'
base_config: experiments/configs/stage1/adaptive_flipped_lasso_exp2_snr.yaml
search_space:
  sigma:
  - 0.1
  - 0.3
  - 0.5
  - 0.7
  - 1.0
  - 1.5
  - 2.0
  - 3.0
fixed_params:
  lambda_ridge: 1.0
  lambda_: 1.0
  gamma: 0.5
best_snr_region:
  sigma:
  - !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      mpmZmZmZuT8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AAAAAAAACEA=
  snr:
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      VVVVVVVV1T8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AAAAAAAAJEA=
sensitivity_analysis:
  f1_corr: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    CKwcWmQ77b8=
  mse_corr: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    RGlv8IXJ7j8=
  tpr_corr: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    +FPjpZvE6r8=
  fdr_corr: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    SgwCK4cW7T8=
  precision_corr: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    SgwCK4cW7b8=
  recall_corr: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    +FPjpZvE6r8=
  r2_corr: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    7nw/NV667b8=
summary:
- sigma: 0.1
  f1_mean: 0.9951
  f1_std: 0.01
  mse_mean: 0.8375
  mse_std: 0.4673
  tpr_mean: 1.0
  tpr_std: 0.0
  fdr_mean: 0.0095
  fdr_std: 0.0194
  precision_mean: 0.9905
  precision_std: 0.0194
  recall_mean: 1.0
  recall_std: 0.0
  r2_mean: 0.9881
  r2_std: 0.0082
  snr: 10.0
- sigma: 0.3
  f1_mean: 0.9769
  f1_std: 0.0359
  mse_mean: 0.9927
  mse_std: 0.4345
  tpr_mean: 1.0
  tpr_std: 0.0
  fdr_mean: 0.0429
  fdr_std: 0.0659
  precision_mean: 0.9571
  precision_std: 0.0659
  recall_mean: 1.0
  recall_std: 0.0
  r2_mean: 0.9861
  r2_std: 0.0079
  snr: 3.33
- sigma: 0.5
  f1_mean: 0.9721
  f1_std: 0.034
  mse_mean: 1.2779
  mse_std: 0.4636
  tpr_mean: 1.0
  tpr_std: 0.0
  fdr_mean: 0.0524
  fdr_std: 0.0622
  precision_mean: 0.9476
  precision_std: 0.0622
  recall_mean: 1.0
  recall_std: 0.0
  r2_mean: 0.9824
  r2_std: 0.0086
  snr: 2.0
- sigma: 0.7
  f1_mean: 0.9579
  f1_std: 0.0307
  mse_mean: 1.6575
  mse_std: 0.4724
  tpr_mean: 1.0
  tpr_std: 0.0
  fdr_mean: 0.0792
  fdr_std: 0.0563
  precision_mean: 0.9208
  precision_std: 0.0563
  recall_mean: 1.0
  recall_std: 0.0
  r2_mean: 0.9776
  r2_std: 0.0092
  snr: 1.43
- sigma: 1.0
  f1_mean: 0.9308
  f1_std: 0.0237
  mse_mean: 2.4648
  mse_std: 0.5301
  tpr_mean: 1.0
  tpr_std: 0.0
  fdr_mean: 0.1285
  fdr_std: 0.0407
  precision_mean: 0.8715
  precision_std: 0.0407
  recall_mean: 1.0
  recall_std: 0.0
  r2_mean: 0.9673
  r2_std: 0.0106
  snr: 1.0
- sigma: 1.5
  f1_mean: 0.8715
  f1_std: 0.0283
  mse_mean: 4.4579
  mse_std: 0.8183
  tpr_mean: 0.98
  tpr_std: 0.025
  fdr_mean: 0.215
  fdr_std: 0.0347
  precision_mean: 0.785
  precision_std: 0.0347
  recall_mean: 0.98
  recall_std: 0.025
  r2_mean: 0.9424
  r2_std: 0.016
  snr: 0.67
- sigma: 2.0
  f1_mean: 0.8232
  f1_std: 0.0399
  mse_mean: 7.0872
  mse_std: 0.9145
  tpr_mean: 0.91
  tpr_std: 0.0595
  fdr_mean: 0.2472
  fdr_std: 0.0369
  precision_mean: 0.7528
  precision_std: 0.0369
  recall_mean: 0.91
  recall_std: 0.0595
  r2_mean: 0.9107
  r2_std: 0.0212
  snr: 0.5
- sigma: 3.0
  f1_mean: 0.669
  f1_std: 0.0918
  mse_mean: 13.3827
  mse_std: 0.9795
  tpr_mean: 0.78
  tpr_std: 0.0692
  fdr_mean: 0.4114
  fdr_std: 0.1043
  precision_mean: 0.5886
  precision_std: 0.1043
  recall_mean: 0.78
  recall_std: 0.0692
  r2_mean: 0.8423
  r2_std: 0.0322
  snr: 0.33
