"""
Debug script to check lambda scale issue
"""
import numpy as np
from unilasso.uni_lasso import cv_unilasso, cv_uni, extract_cv
from experiment_ar1 import generate_data

# Generate small test data
np.random.seed(42)
X_train, y_train, X_test, y_test, beta_true, true_indices = generate_data(
    n=300, p=1000, sigma=1.0, rho=0.8
)

print(f"True non-zero coefficients: {len(true_indices)}")
print(f"True beta range: [{beta_true.min():.2f}, {beta_true.max():.2f}]")

# Test 1: Original UniLasso for baseline
print("\n=== Test 1: Original UniLasso ===")
cv_result_uni = cv_unilasso(
    X_train, y_train, family="gaussian", n_folds=5, verbose=False
)
fit_uni = extract_cv(cv_result_uni)
y_pred_uni = X_test @ fit_uni.coefs + fit_uni.intercept
mse_uni = np.mean((y_pred_uni - y_test) ** 2)
selected_uni = np.sum(np.abs(fit_uni.coefs) > 1e-8)
tpr_uni = len(np.intersect1d(np.where(np.abs(fit_uni.coefs) > 1e-8)[0], true_indices)) / len(true_indices)
print(f"MSE: {mse_uni:.3f}")
print(f"Selected variables: {selected_uni}")
print(f"TPR: {tpr_uni:.3f}")
print(f"Best lambda: {cv_result_uni.best_lmda:.6f}")

# Test 2: XLasso with current lambda scaling (100x)
print("\n=== Test 2: XLasso (current 100x lambda scaling) ===")
cv_result_xl = cv_uni(
    X_train, y_train, family="gaussian", n_folds=5,
    adaptive_weighting=False,
    enable_group_constraint=False,
    alpha=0.0,
    beta=1.0,
    backend="numba",
    verbose=False
)
fit_xl = extract_cv(cv_result_xl)
y_pred_xl = X_test @ fit_xl.coefs + fit_xl.intercept
mse_xl = np.mean((y_pred_xl - y_test) ** 2)
selected_xl = np.sum(np.abs(fit_xl.coefs) > 1e-8)
tpr_xl = len(np.intersect1d(np.where(np.abs(fit_xl.coefs) > 1e-8)[0], true_indices)) / len(true_indices)
print(f"MSE: {mse_xl:.3f}")
print(f"Selected variables: {selected_xl}")
print(f"TPR: {tpr_xl:.3f}")
print(f"Best lambda: {cv_result_xl.best_lmda:.6f}")
print(f"Lambda range: [{cv_result_xl.lmdas.min():.6f}, {cv_result_xl.lmdas.max():.6f}]")

# Let's also check the lambda values generated by _configure_lmda_path
from unilasso.uni_lasso import _configure_lmda_path, _prepare_unilasso_input

print("\n=== Lambda scale analysis ===")
X, y, loo_fits, beta_intercepts, beta_coefs_fit, glm_family, _, original_lmdas, zero_var_idx = _prepare_unilasso_input(
    X_train, y_train, "gaussian", None
)

lambda_path = _configure_lmda_path(
    X=loo_fits,
    y=y,
    family="gaussian",
    n_lmdas=100,
    lmda_min_ratio=1e-2
)
print(f"Original lambda path (no scaling): min={lambda_path.min():.6f}, max={lambda_path.max():.6f}")
print(f"After 100x scaling: min={lambda_path.min()*100:.6f}, max={lambda_path.max()*100:.6f}")
print(f"UniLasso best lambda: {cv_result_uni.best_lmda:.6f}")
print(f"Ratio between UniLasso best lambda and max unscaled lambda: {cv_result_uni.best_lmda / lambda_path.max():.2f}x")
